---
title: "Melrose Police Log"
author: "Kwan Lin"
date: "7/19/2017"
output:
  hrbrthemes::ipsum:
    keep_md: true
editor_options:
  chunk_output_type: inline
---

# Setup

```{r setup, include=FALSE}
#setwd(dir = "~/projects/melrose_police_log/")
#knitr::opts_knit$set(root.dir = "~/pro jects/melrose_police_log/")
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE,
                      echo=FALSE,
                      fig.retina=2,
                      dev=c("png"))
```

```{r packages}
# library(devtools)
library(tidyverse)
library(rprojroot)
library(rvest)
library(httr)
library(pbapply)
library(stringr)
library(lubridate)
# library(officer)
library(textreadr)
library(ggmap)
# library(nominatim) # devtools::install_github("hrbrmstr/nominatim")

# themes
library(hrbrthemes)
library(ggthemes)
```

```{r paths}
root_path <- find_rstudio_root_file()
```

# Overview

This is a project to extract and analyze data from Melrose police logs.

# References

https://stackoverflow.com/questions/33790052/download-all-files-from-a-folder-on-a-website

https://stackoverflow.com/questions/30790114/applying-same-function-on-multiple-files-in-r

https://stackoverflow.com/questions/32504880/street-address-to-geolocation-lat-long

https://www.jessesadler.com/post/geocoding-with-r/

# Data

```{r scrape-melrose-police-logs, eval=FALSE}
log_url <- "https://melrosepolice.net/police-logs/"

url_contents <- read_html(log_url)

docs <- grep("docx", html_attr(html_nodes(url_contents, "a[href]"), "href"), value=TRUE)


# ignore errors
options(warn = -1)

# apply to a list of urls for .docx files - download each file to a path. includes error handling
lapply(docs, function(x) tryCatch(download.file(x,paste0(root_path,"/data/",basename(x))),
                                  error = function(e) print(paste(basename(x), 'did not work out'))))

# saveRDS(object, file = paste0(root_path,"/data/object.rds"))
```

```{r parse_function}
parse_log <- function(file_path) {
  file_contents <- textreadr::read_docx(file_path)
  
  file_df <- as.data.frame(file_contents)
  
  parse_df <- file_df %>%
    filter(grepl("\\d{0,}-\\d{1,} \\d{4}|Location|Vicinity|Date", file_contents)) %>%
    mutate(date_tag = ifelse(grepl("Date",file_contents), 1, 0)) %>%
    mutate(datestamp = ifelse(grepl("Date",file_contents), stringr::str_extract(file_contents, "\\d+/\\d+/\\d+"),NA)) %>%
    fill(datestamp) %>%
    filter(!grepl("Date",file_contents)) %>%
    mutate(incident_tag = ifelse(grepl("\\d{0,}-\\d{1,} \\d{4}", file_contents),1,0)) %>%
    mutate(inc_cnt = cumsum(incident_tag)) %>%
    spread(incident_tag, file_contents) %>%
    janitor::clean_names() 
  
  return(parse_df)
}

```

```{r loop-over-all-files, eval=FALSE}
# log_files <- list.files("../data/", ".docx")
log_files <- paste0("../data/", list.files("../data/", ".docx")) # exact relative path

merged_logs <- do.call(rbind,lapply(log_files, function(x) tryCatch(parse_log(x),
                                       error = function(e) print(paste(x, "caused an error")))))

write_csv(merged_logs, "../output/merged_logs.csv")
```

In total, 10 files (as of 11/16/2018) from police log set were not usable: 2 were 404 on the website, remainder had incident ID's missing that compromised the data parsing process.

```{r debug-data, eval = FALSE}
# TODO - fix file issues
# [1] "../data/Melrose-Police-Department-Dispatch-09-07-2015-thru-09-14-2015.docx caused an error" - identified issue: some records have no incident id
# [1] "../data/Melrose-Police-Department-Dispatch-Log-8-17-2015-Thru-8-24-2015.docx caused an error" - corrupt file?
# [1] "../data/Melrose-Police-Department-press-log-April-27-2015-May-4-2015.docx caused an error" - identified issue: some records have no incident id
# [1] "../data/Melrose-Police-Log-5-25-2015-thru-6-1-2015.docx caused an error" - identified issue: some records have no incident id 
# [1] "../data/MPD-Dispatch-Log-Feb-13-to-Feb-19.docx caused an error"
# [1] "../data/MPD-Dispatch-Log-Jan-29-to-Feb-4.docx caused an error"
# [1] "../data/MPD-Dispatch-Log-July-10-to-July-16.docx caused an error"
# [1] "../data/MPD-Dispatch-Log-Sept-24-to-Sept-30.docx caused an error"

# usage: take a known error file, assign it to variable, then start debugging

error_file <- "../data/Melrose-Police-Log-5-25-2015-thru-6-1-2015.docx"

parse_log(error_file)

file_contents <- textreadr::read_docx(error_file)
  
file_df <- as.data.frame(file_contents)

parse_df <- file_df %>%
  filter(grepl("\\d{0,}-\\d{1,} \\d{4}|Location|Vicinity|Date", file_contents)) %>%
  mutate(date_tag = ifelse(grepl("Date",file_contents), 1, 0)) %>%
  mutate(datestamp = ifelse(grepl("Date",file_contents), stringr::str_extract(file_contents, "\\d+/\\d+/\\d+"),NA)) %>%
  fill(datestamp) %>%
  filter(!grepl("Date",file_contents)) %>%
  mutate(incident_tag = ifelse(grepl("\\d{0,}-\\d{1,} \\d{4}", file_contents),1,0)) %>%
  mutate(inc_cnt = cumsum(incident_tag)) # %>%
  spread(incident_tag, file_contents) 

```


```{r prep-data}
merged_logs <- read_csv("../output/merged_logs.csv")

prep_dat <- merged_logs %>%
  mutate(location_raw = gsub("Location/Address: |Vicinity of: ", "", x0)) %>%
  # mutate(location_split = strsplit(location_raw, " - ")) %>%
  mutate(location_name = stringr::str_extract(location_raw, "^(.+?) - "),
         location_name = gsub(" - ", "", location_name),
         location_name = trimws(location_name)) %>%
  mutate(location_addr = gsub("^(.+?) - ","", location_raw),
         # location_addr = gsub("Apt.(.+?)$","", location_addr),
         location_addr = gsub("@.*","", location_addr),
         location_addr = gsub("Apt.*","", location_addr),
         location_addr = gsub("Location:","", location_addr),
         location_addr = gsub("\\[.*\\]","", location_addr),
         location_addr = trimws(location_addr)# ,
         # location_addr = paste0(location_addr, ", Melrose, MA")
         ) %>%
  mutate(incident_id = stringr::str_extract(x1, "\\d{0,}-\\d{1,}")) %>% # \\d{4}
  mutate(hour_min = stringr::str_extract(x1, " \\d{4}")) %>%
  # rename("description_raw" = "x1") %>%
  mutate(description_raw = gsub("\\d{0,}-\\d{1,} \\d{4}","", x1),
         description_raw = trimws(description_raw)) %>%
  mutate(datestamp = mdy(datestamp),
         year = year(datestamp),
         month = month(datestamp),
         date = date(datestamp)) %>%
  # mutate(accident = ifelse(grepl("ACCIDENT|accident", x1), 1, 0)) %>%
  select(-c(date_tag, inc_cnt, location_raw, x1)) # x0 was the origincal location/address row 

# location_addr <- unique(prep_dat$location_addr)

# loc_distinct <- distinct(prep_dat, location_addr)


```

# Analysis

## Accidents 

```{r accident-dat}
accident_dat <- prep_dat %>%
  filter(grepl("accident", description_raw, ignore.case = TRUE))
```

```{r street count}
street_dat <- accident_dat %>%
  mutate(street = gsub("[0-9]","",location_addr),
         street = trimws(street),
         street = case_when(
           street == "LYNN FELLS" ~ "LYNN FELLS PKWY",
           street == "LYNN FELLS P" ~ "LYNN FELLS PKWY",
           street == "LYNN FELLS PKWY FELLS" ~ "LYNN FELLS PKWY",
           street == "LYNN FELLS PKWY P" ~ "LYNN FELLS PKWY",
           street == "MAIN" ~ "MAIN ST",
           street == "WEST EMERSON ST" ~ "W EMERSON ST",
           TRUE ~ street
         ))

top_street <- street_dat %>%
  count(street) %>%
  arrange(desc(n)) %>%
  top_n(30)

```

```{r bar-street-accidents-all, fig.width = 10, fig.height= 20}
street_dat %>%  
  count(street) %>%
  filter(!is.na(year)) %>%
  filter(!is.na(street)) %>%
  # filter(street %in% top_street$street) %>%
  ggplot(aes(x = reorder(street, n), y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  # theme_ipsum() +
  theme_ipsum() +
  scale_y_continuous(limits = c(0,375), breaks = seq(0, 400, 50)) +
  theme(axis.text.y = element_text(size = 7)) +
  labs(title = "Accidents in Melrose by Street between 2015-2018",
       # subtitle = "Subset to the streets with the most accidents between 2015-2018",
       caption = "Source: Melrose Police Logs",
       x = NULL,
       y = "Accident count")
```

```{r bar-street-accidents-top, fig.width = 16, fig.height= 8}
street_dat %>%  
  count(street, year) %>%
  filter(!is.na(year)) %>%
  filter(!is.na(street)) %>%
  filter(street %in% top_street$street) %>%
  ggplot(aes(x = reorder(street, desc(street)), y = n)) +
  facet_wrap(~year, nrow = 1) +
  geom_bar(stat = "identity") +
  # scale_y_continuous(name = "Count of accidents", 
  #                  limits=c(0.1, 100),
  #                  breaks = seq(0, 100, 10)) +
  coord_flip() +
  # theme_fivethirtyeight() +
  scale_y_continuous(limits = c(0,90), breaks = seq(0, 90, 10)) +
  theme_ipsum() +
  theme(axis.text.y = element_text(size = 8),
        axis.title.y = element_text(vjust = .5)) +
  # opts(axis.title.y = theme_text(vjust=-0.5)) +
  labs(title = "Accidents in Melrose by Street",
       subtitle = "Subset to top 30 streets with the most accidents between 2015-2018.",
       caption = "Source: Melrose Police Logs",
       x = NULL,
       y = "Number of accidents")
```

```{r lynn-fells-accidents, fig.width=12, fig.height=5, eval=FALSE}
accident_dat %>%
  filter(grepl("LYNN FELLS", location_addr)) %>%
  mutate(lynn_fells_num = as.numeric(str_extract(location_addr, "[0-9]*"))) %>%
  select(year, lynn_fells_num) %>%
  ggplot(aes(x = lynn_fells_num)) +
  geom_histogram(bins = 50) +
  # geom_text("")
  geom_vline(xintercept = 240, color = "red", linetype = "dashed") + # Vinton
  annotate("text", label = "Vinton St.", x = 265, y = 11, color = "red", size = 3) +
  geom_vline(xintercept = 355, color = "red", linetype = "dashed") + # Vinton
  annotate("text", label = "Melrose High School", x = 400, y = 11, color = "red", size = 3) +
  facet_wrap(~year, ncol = 1) +
  theme_fivethirtyeight() +
  labs(title = "Histogram of accidents along Lynn Fells Parkway in Melrose",
       subtitle = "X-axis corresponds to numbering of Lynn Fells Parkway.")
  
```

```{r lynn-fells-points-facet-year, fig.width=12, fig.height=10}
accident_dat %>%
  filter(grepl("LYNN FELLS", location_addr)) %>%
  mutate(lynn_fells_num = as.numeric(str_extract(location_addr, "[0-9]*")),
         hour = as.numeric(substr(hour_min, 0,3))) %>%
  select(year, lynn_fells_num, hour) %>%
  ggplot(aes(x = lynn_fells_num, y = hour)) +
  # geom_jitter(aes(color = as.factor(year)), alpha = 1/3, size =2) +
  geom_point(alpha = 1/3, size = 3, color = "blue") +
  # geom_text("")
  geom_vline(xintercept = 6, color = "red", linetype = "dashed") +
  annotate("text", label = "'Welcome to Melrose' sign", x = 65, y = 26, color = "red", size = 3) +
  # geom_vline(xintercept = 230, color = "red", linetype = "dashed") +
  # annotate("text", label = "Vinton St.", x = 265, y = 26, color = "red", size = 3) +
  geom_vline(xintercept = 350, color = "red", linetype = "dashed") +
  annotate("text", label = "Melrose High School", x = 400, y = 26, color = "red", size = 3) +
  geom_vline(xintercept = 470, color = "red", linetype = "dashed") + 
  annotate("text", label = "Whole Foods", x = 500, y = 26, color = "red", size = 3) +
  geom_vline(xintercept = 542.5, color = "red", linetype = "dashed") + 
  annotate("text", label = "Bellevue Ave.", x = 575, y = 26, color = "red", size = 3) +
  geom_vline(xintercept = 680, color = "red", linetype = "dashed") + 
  annotate("text", label = "Lincoln St.", x = 705, y = 26, color = "red", size = 3) +
  facet_wrap(~year, ncol = 1) +
  scale_x_continuous(name = "Nearest street number along Lynn Fells Parkway where accident occurred", 
                     limits=c(0.1, 800),
                     breaks = seq(0, 800, 50)) +
  scale_y_continuous(name = "Hour of day", 
                     limits=c(0, 26.5),
                     breaks = seq(0, 24, 4)) +
  labs(title = "Accidents along Lynn Fells Parkway in Melrose",
       subtitle = "Each point corresponds to a distinct accident where street number was made available.\nOverlapping points appear darker.",
       caption = "Source: Melrose Police Logs",
       x = "Nearest street number along Lynn Fells Parkway where accident occurred",
       y = "Hour of day"
       ) +
  # theme_fivethirtyeight()
  theme_grey()
  
```

```{r main-st-points-facet-year, fig.width=12, fig.height=10}
accident_dat %>%
  filter(grepl("MAIN", location_addr)) %>%
  filter(!is.na(year)) %>%
  mutate(main_st_num = as.numeric(str_extract(location_addr, "[0-9]*")),
         hour = as.numeric(substr(hour_min, 0,3))) %>%
  select(year, main_st_num, hour) %>%
  ggplot(aes(x = main_st_num, y = hour)) +
  # geom_jitter(aes(color = as.factor(year)), alpha = 1/3, size =2) +
  geom_point(alpha = 1/3, size = 3, color = "blue") +
  # geom_text("")
  geom_vline(xintercept = 314, color = "red", linetype = "dashed") +
  annotate("text", label = "W/E Wyoming St.", x = 355, y = 26, color = "red", size = 3) +
  geom_vline(xintercept = 400, color = "red", linetype = "dashed") +
  annotate("text", label = "Grove St.", x = 423, y = 26, color = "red", size = 3) +
  geom_vline(xintercept = 497, color = "red", linetype = "dashed") +
  annotate("text", label = "W/E Foster St.", x = 530, y = 26, color = "red", size = 3) +
  geom_vline(xintercept = 546, color = "red", linetype = "dashed") +
  annotate("text", label = "Upham St.", x = 570, y = 24, color = "red", size = 3) +
  facet_wrap(~year, ncol = 1) +
  scale_x_continuous(name = "Nearest street number along Main St. where accident occurred", 
                     limits=c(0.1, 800),
                     breaks = seq(0, 800, 50)) +
  scale_y_continuous(name = "Hour of day", 
                     limits=c(0, 26.5),
                     breaks = seq(0, 24, 4)) +
  labs(title = "Accidents along Main St. in Melrose",
       subtitle = "Each point corresponds to a distinct accident where street number was made available.\nOverlapping points appear darker.",
       caption = "Source: Melrose Police Logs",
       # x = "Nearest street number along Lynn Fells Parkway where accident occurred",
       y = "Hour of day"
       ) +
  # theme_fivethirtyeight()
  theme_grey()
  
# accident_dat %>%
#   filter(grepl("MAIN", location_addr)) %>%
#   filter(!is.na(year)) %>%
#   mutate(main_st_num = as.numeric(str_extract(location_addr, "[0-9]*")),
#          hour = as.numeric(substr(hour_min, 0,3))) %>%
#   select(year, main_st_num, hour) %>% View()
```

```{r top-street-month, eval=FALSE}
street_dat %>%
  left_join(top_street, by = c("street" = "street")) %>%
  count(street, year, month) %>%
  ggplot()
```

```{r geocode-addresses, eval=FALSE}
# TODO

# Initialize the data frame
accident_loc_distinct <- distinct(accident_dat, location_addr)

test_loc_distinct <- sample_n(accident_loc_distinct, 10)
test_loc_distinct_geo <- mutate_geocode(test_loc_distinct, location_addr)
```